apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-gateway
  template:
    metadata:
      labels:
        app: game-gateway
    spec:
      containers:
      - name: game-gateway
        image: spaceship-gateway:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: AUTH_API_URL
          value: "http://auth-service:5000/api/auth"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: game-gateway
spec:
  ports:
  - port: 3000
  selector:
    app: game-gateway
